services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/storage:/app/storage
    environment:
      - UPLOAD_DIR=/app/uploads
      - STORAGE_DIR=/app/storage
      - ANONYMIZED_TELEMETRY=False

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_PROXY_TARGET=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev
